### ISSUE TITLE
stuff to do

### ISSUE THREAD

**Issue by andrewpbray** [gradebook-dev/gradebook#3]
- [x] Add policy file to package (inspired by data 88E)
- [x] Document `gs_demo` and `policy_demo`.
- [x] Add validate-policy.r. That and validate-gs can be thin to start but over time can be pretty exhaustive. Can compare to scheme for gs and policy that we keep within the package.

Please feel free to edit / add to the excalidraw: https://app.excalidraw.com/s/4AKpAITWs2z/5mcvzNSuDhn

**Comment by andrewpbray** [comment]
- [ ]

**Comment by andrewpbray** [comment]
- [ ] Add in `merge_files.R` functions and documentation.
- [ ] Add in `calculate_grades.R` functions and documentation.
- [ ] Flesh out GS Demo vignette, going through each function and showing the reader what the difference is in the input and output. (ping me once you have the sxa + policy combined and dicussed in the vignette).

**Comment by andrewpbray** [comment]
[ ] Redo excalidraw diagram so that the rectangles are pipeable functions instead of .R files.

**Comment by mvoutov** [comment]
[ ] Add tests to `get_id_cols() `
